import netCDF4
from netCDF4 import Dataset
import xarray as xr
# sresa1b_ncar_ccsm3-example.nc
file = xr.open_dataset('./test.nc')
"""
Data variables:
    area       (lat, lon) float32 ...
    lat_bnds   (lat, bnds) float64 ...
    lon_bnds   (lon, bnds) float64 ...
    msk_rgn    (lat, lon) int32 ...
    pr         (time, lat, lon) float32 ...
    tas        (time, lat, lon) float32 ...
    time_bnds  (time, bnds) object ...
    ua         (time, plev, lat, lon) float32 ...
"""
# print all netCDF
# print(file["area"].shape)
# (128, 256)
# Dimensions:    (lat: 128, lon: 256, bnds: 2, plev: 17, time: 1)
# print(file["lon_bnds"].shape)
# (256, 2)
print(file.pr.shape) # (1, 128, 256)
print(file.tas.shape) # (1, 128, 256)
print(type(file.variables)) # <class 'xarray.core.utils.Frozen'>